### ISSUE TITLE
 easeprod  start error

### ISSUE THREAD

**Issue by hongery** [megaease/easeprobe#163]
/opt # easeprobe -f config.yaml 
INFO[0000] The data file data/data.yaml, was not found! 
INFO[0000] Load the configuration file successfully!    
INFO[0000] Successfully created the PID file: /opt/easeprobe.pid 
INFO[0000] Application Log File [Stdout] - Self-Rotate  
INFO[0000] Web Access Log File [Stdout] - Self-Rotate   
INFO[2022-07-05T03:44:22Z] [Web] HTTP server is listening on 0.0.0.0:8181 
INFO[2022-07-05T03:44:22Z] Probe [http] - [ElasticSearch] base options are configured! 
INFO[2022-07-05T03:44:22Z] [Metric] Counter <EaseProbe_http_total> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_duration> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_status> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_sla> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Counter <EaseProbe_http_status_code> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_content_len> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_dns_duration> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_connect_duration> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_tls_duration> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_send_duration> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_wait_duration> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_transfer_duration> is created! 
INFO[2022-07-05T03:44:22Z] [Metric] Gauge <EaseProbe_http_total_duration> is created! 
FATA[2022-07-05T03:44:22Z] No notifies configured, exiting...  

config.yaml
```
http:
  - name: test
    url: http://xxxx.com
```

**Comment by haoel** [comment]
as the error message mentioned, you need to configure a notification.

**Comment by hongery** [comment]
solve！

**Comment by haoel** [comment]
404 considering is good. the default valid status code is [0-499], if you need to customize it you can configure:

```yaml
http:
    - name : test
      url: http://10.61.101.65:8000
      success_code:
          - [200,206] # the code >=200 and <= 206
          - [300,308] # the code >=300 and <= 308
```

Please read the readme for more information: https://github.com/megaease/easeprobe#31-http-probe-configuration

**Comment by hongery** [comment]
> 
data.yaml
```
---
name: EaseProbe
version: v1.7.0
---
test:
    name: test
    endpoint: http://10.61.101.65:8000/accounts
    time: 2022-07-05T06:08:59.725688132Z
    timestamp: 0
    rtt: 0s
    status: init
    prestatus: init
    message: Good Configuration!
    latestdowntime: 0001-01-01T00:00:00Z
    recoverytime: 0s
    stat:
        since: 2022-07-05T06:08:59.725688175Z
        total: 0
        status: {}
        uptime: 0s
        downtime: 0s
    timeformat: 2006-01-02 15:04:05 UTC

```
config.yaml
```
http:
  # Some of the Software support the HTTP Query
  - name: test
    method: GET
    url: http://10.61.101.65:8000/accounts
    #content_encoding: text/json
    success_code:
      - [200,502]
    timeout: 10s # default is 30 seconds
notify:
    # dry: true # Global settings for dry run
    retry: # Global settings for retry
    times: 5
    interval: 10s
    log:
     - name: "log file"
       file: "/tmp/easeprobe"
```

http request
```
2022/07/05 14:11:32 Reporting span 36f22974c7f82fd4:36f22974c7f82fd4:0000000000000000:1
[GIN] 2022/07/05 - 14:11:32 | 200 |     240.566µs |      172.17.0.4 | GET      "/accounts"
```
