### ISSUE TITLE
shell content error, no dingding message send

### ISSUE THREAD

**Issue by studyhuang1996** [megaease/easeprobe#165]
**Enviornment (please complete the following information):**
 - OS: linux 
 - EaseProbe Version 
 - latest version

**Describe the bug**
配置shell脚本，脚本内容出错，钉钉消息未发送通知，日志也未打印发送钉钉通知消息
Configure shell script, script error, but messages are not sent to DingDing notifications, and there is no notifcaiton logs  as well.

![image](https://user-images.githubusercontent.com/27665214/177911837-f77a4b5b-ebb8-4cc7-b7d0-9858a542ffbf.png)

**To Reproduce**

**Expected behavior**
期望脚本报错发送钉钉消息，如果是钉钉配置出错，希望把日志打印出来

**Comment by haoel** [comment]
what's the config.yaml? how to reproduce this problem?

BTW, next time, please paste the log as text instead of a picture.

**Comment by haoel** [comment]
By the way, the EaseProbe is edge-trigger, which means only the status change (up -> down, or down -> up) would send the notification. 

if the "Flink Monitor" script had been run failed already,  which means the status just from `down` to `down`, this won't trigger the notification.

you can enable the debug information to check

```yaml
settings:
   log:
       level: debug
```

**Comment by studyhuang1996** [comment]
刚那个问题是脚本内容出错，状态是 down=>down no state change 所以没有通知，已解决，感谢。不过想知道，对于钉钉消息的内容展示，是否用户可以自定义内容。可以有提供个消息模版参数，可由用户自己进行定制

**Comment by haoel** [comment]
can you can give proposal what the template looks like? And feel free to
contribute what you want.

studyhuang1996 ***@***.***>于2022年7月8日 周五15:07写道：

**Comment by studyhuang1996** [comment]
![image](https://user-images.githubusercontent.com/27665214/177942109-edc720d4-b472-4047-8747-c519e6b07aa3.png)
可否 每个任务下脚本下可自定义自己的message，然后钉钉消息，从message中获取, 还有个问题，请问下yaml 只有响应检查只有 not_contain 和  contain 吗？ 可否有个 或者 。比如我请求一个接口，解析接口中返回值获取某个字段值，比如这个字段有 
[a,b,c,d,e] 多种状态，那么我此时想判断 文本中 存在 b或者 c 就算失败，单单包含貌似满足不了需求

**Comment by haoel** [comment]
You can do any check in your script, and output any message you like. EaseProbe would send that message to notification.

**Comment by haoel** [comment]
@studyhuang1996 do you have any further questions?

**Comment by studyhuang1996** [comment]
日志展示：10点43分的时候 推送钉钉消息
ERRO[2022-07-12T10:43:26+08:00] [shell / 93-Flink Job监控] - the output does not contain [成功]
INFO[2022-07-12T10:43:26+08:00] [channel / __EaseProbe_Channel__]: 93-Flink Job监控 (/home/soft/easeprobe/script/flink-monitor.sh http://127.0.0.1:19960/jobs/overview) - Status changed [up] ==> [down]
INFO[2022-07-12T10:43:26+08:00] [dingtalk / dingtalk alert service] - **93-Flink Job监控 Failure** ❌
/home/soft/easeprobe/script/flink-monitor.sh http://192.168.0.93:8081/jobs/overview - ⏱ 12ms
Error (shell): Error: the output does not contain [成功]
但是实际没有发送钉钉消息，钉钉消息只有 10点41分的时候，运行发送一次
![image](https://user-images.githubusercontent.com/27665214/178399434-f91b9f20-a4b4-4969-89b6-15a92683eeb7.png)

消息提醒日期，可以自定义展示 UTC+8 东八区吗？

**Comment by haoel** [comment]
1) any error message for DingTalk notification?  if not,  can you enable the debug logging to see what's happening?   you can set the following configuration to enable it.

```yaml
settings:
    log:
        level: debug
````

2) the time zone you can configure that, but you need to use the latest source code to build because I just supported that yesterday in PR #166 


**BTW, please paste the code, log, and configuration with markdown format instead of a picture!!!!**

**Comment by studyhuang1996** [comment]
1. 日志没有钉钉相关错误消息
`job执行失败!
ERRO[2022-07-12T11:21:38+08:00] [shell / 93-Flink Job监控] - the output does not contain [成功]
DEBU[2022-07-12T11:21:38+08:00] [shell / 93-Flink Job监控] - Error: the output does not contain [成功]
DEBU[2022-07-12T11:21:38+08:00] shell: {"name":"93-Flink Job监控","endpoint":"/home/soft/easeprobe/script/flink-monitor.sh http://127.0.0.1:8081/jobs/overview","time":"2022-07-12T03:21:38.643645189Z","timestamp":1657596098643,"rtt":10581020,"status":"down","prestatus":"up","message":"Error (shell): Error: the output does not contain [成功]","latestdowntime":"2022-07-12T03:21:38.654243334Z","recoverytime":1500051839778,"stat":{"since":"2022-07-11T08:32:02.254268601Z","total":208,"status":{"1":183,"2":25},"uptime":54900000000000,"downtime":7500000000000},"timeformat":"2006-01-02 15:04:05 UTC"}
INFO[2022-07-12T11:21:38+08:00] [channel / __EaseProbe_Channel__]: 93-Flink Job监控 (/home/soft/easeprobe/script/flink-monitor.sh http://127.0.0.1:8081/jobs/overview) - Status changed [up] ==> [down]
INFO[2022-07-12T11:21:38+08:00] [dingtalk / dingtalk alert service] - **93-Flink Job监控 Failure** ❌
/home/soft/easeprobe/script/flink-monitor.sh http://127.0.0.1:8081/jobs/overview - ⏱ 11ms
Error (shell): Error: the output does not contain [成功]
> EaseProbe v1.6.0 @ localhost.localdomain at 2022-07-12 03:21:38 UTC


2022/07/12 11:22:38 "GET http://127.0.0.1:8181/ HTTP/1.1" from 192.168.11.108:56490 - 200 2092B in 78.417µs
2022/07/12 11:22:39 "GET http://127.0.0.1:8181/favicon.ico HTTP/1.1" from 192.168.11.108:56490 - 200 2092B in 63.413µs`

**Comment by haoel** [comment]
it should have a log state `successfully sent!` or `failed to send!`,  
and if there have some connection problem with the DingTalk server, it should have a Warning log for retry... 

can you find those logs?

**Comment by haoel** [comment]
By the way, it looks you enable the dry run mode for DingTalk, could you please show your `config.yaml`?

**Comment by studyhuang1996** [comment]
> By the way, it looks you enable the dry run mode for DingTalk, could you please show your `config.yaml`?
配置如下:
```
#Shell Probe Configuration
shell:
  # A proxy curl shell script
  - name: 93-Flink Job监控
    cmd: "/home/soft/easeprobe/script/flink-monitor.sh"
    args:
      - "http://127.0.0.1:8081/jobs/overview"
    contain: "成功"
# Native Client Probe
client:
  - name: 125-MySQL从库监控
    driver: "mysql"
    host: "127.0.0.1:3306"
    username: "root"
    password: "***"



settings:
  log:
    level: debug
  sla:
    schedule : "daily"
    time: "23:00"
  probe:
    interval: 5m
  http:
    ip: 127.0.0.1
    port: 8181






notify:
  dingtalk:
    - name: "dingtalk alert service"
      webhook: "https://oapi.dingtalk.com/robot/send?access_token=****"


```
