### ISSUE TITLE
Native  MongoDB Client  如何配置复制集

### ISSUE THREAD

**Issue by triumph** [megaease/easeprobe#175]
老师辛苦了， 如何配置  mongo复制集监控呢？ 谢谢

   说明文档上，只有单机版的。
  - name: MongoDB Native Client
    driver: "mongo"
    host: "192.168.28.171:27117"

**Comment by haoel** [comment]
You can config multiple MongoDB nodes.  please be aware of the `name`, you can name them with the convention you like, and show them belong to the same cluster. 

for example:

```yaml
client:
   - name : MongoDB-Cluster-Production-Master-01
      driver: "mongo"
      host: 192.168.1.1:27117
   - name : MongoDB-Cluster-Production-Master-02
      driver: "mongo"
      host: 192.168.1.2:27117
   - name : MongoDB-Cluster-Production-Master-03
      driver: "mongo"
      host: 192.168.1.3:27117
   - name : MongoDB-Cluster-Production-Replica-01
      driver: "mongo"
      host: 192.168.1.11:27117
   - name : MongoDB-Cluster-Production-Replica-02
      driver: "mongo"
      host: 192.168.1.12:27117
   - name : MongoDB-Cluster-Production-Replica-03
      driver: "mongo"
      host: 192.168.1.13:27117
```
