### ISSUE TITLE
every hourly Restart stat up and down times

### ISSUE THREAD

**Issue by hongery** [megaease/easeprobe#179]
$CMD/data/data.yaml 
I want to stat up and down times,start from zero.every hourly.
How it should be configured？
```
---
name: EaseProbe
version: v1.7.0
---
"":
    name: ""
    endpoint: http://xxxxx:8000/accounts
    time: 2022-07-25T03:40:09.881474243Z
    timestamp: 1658720409881
    rtt: 354.042µs
    status: down
    prestatus: down
    message: 'Error (http): Error: Get "http://xxxx:8000/accounts": dial tcp xxxxx:8000: connect: connection refused'
    latestdowntime: 2022-07-25T02:44:48.241836769Z
    recoverytime: 0s
    stat:
        since: 2022-07-07T02:49:31.152596481Z
        total: 1454
        status:
            up: 1412
            down: 42
        uptime: 23h32m0s
        downtime: 42m0s
    timeformat: 2006-01-02 15:04:05 UTC
```
