### ISSUE TITLE
How can I add labels to the metrics?

### ISSUE THREAD

**Issue by Zhang21** [megaease/easeprobe#368]
**My problem**

How can I add  labels to the metrics? Such as custom labels or information of config.yaml file。

demo `config.yaml`:

```yml
# just tcp example
tcp:
  - name: tcp-22
    host: 127.0.0.1:22
    group: test
  - name: tcp-3306
    host: 127.0.0.1:3306
```

the metrics like:

```
EaseProbe_tcp_status{instance="127.0.0.1:8081",job="easeprobe",name="tcp-22"}
EaseProbe_tcp_status{instance="127.0.0.1:8081",job="easeprobe",name="tcp-3306"} 
```
