### ISSUE TITLE
Add constant labels for Prometheus metrics

### ISSUE THREAD

**Issue by qdongxu** [megaease/easeprobe#385]
**Background & X Problem**

**EaseProbe** probes a large number of endpoints, but currently labels can only be configured in the Prometheus scrape_configs, this can only label the probe itself.  

**Proposal and Expectation**
 It's expected that EaseProble behaves as a local exporter on the target node and the labels specific to the target nodes. 

**Solutions & Y Problems**

Propose to add a  `labels` item to each probe module, which contains constant labels. Here's a example, adding constant labels to an HTTP prober.

```yaml
   http:
     - name: Web Service
       url: http://example.com:1080
       labels:
          service: web_example
          env: wg-idc-prod
       alert:
         strategy: regular
         factor: 
```
the corresponding Prometheus metric looks like:

> EaseProbe_http_status{env="wg-idc-prod", endpoint="http://example.com:1080", instance="127.0.0.1:8181", job="easeprobe", name="Web Service", service="web_example"}

**Additional context**
