### ISSUE TITLE
Using the increase() function on the Prometheus metric EaseProbe_client_kafka_total returns 0  

### ISSUE THREAD

**Issue by MuChenMuXuan** [megaease/easeprobe#442]
**Environment (please complete the following information):**
 - OS: Linux mockapi 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 - EaseProbe Version v2.1.1

**Describe the bug**
kafka client probe, the config is:
```
client:
  - name: Kafka Native Client node0
    driver: "kafka"
    host: "10.25.48.95:9092"
  - name: Kafka Native Client node1
    driver: "kafka"
    host: "10.29.46.118:9092"
  - name: Kafka Native Client node2
    driver: "kafka"
    host: "10.30.84.216:9092"
```

when node0 down, then it produce prometheus metric:
<img width="1889" alt="image" src="https://github.com/megaease/easeprobe/assets/3232275/abe214c3-93b9-494c-a71e-fe0bd0fd2d15">

Then monitor it via PromQL:
<img width="925" alt="image" src="https://github.com/megaease/easeprobe/assets/3232275/f181f791-0c5d-424c-b852-b1e28d6ccfda">

Referring to this article at 
[link](https://stackoverflow.com/questions/67985867/why-is-increase-showing-only-zero-values-when-i-can-see-the-metric-value-incre)
I believe it's because the label {status=''down"} lacks an initial value. 

I'm unsure how to write PromQL to monitor this metric. 

Additionally, the value of total{status='up'} keeps increasing continuously (similar to a counter), while the value of total{status='down'} remains constant (the metric remained at 3 for approximately 15 minutes when the Kafka service was down). 

Assuming the probe's detection occurs every 1 minute, the value of total{status='down'} should increase by 1 each time it's probed. If that's the case, using the increase() function should make it easier to detect such anomalies."

I've thought of a compromise, which involves monitoring the increment of the value for total{status='up'}. If the increment is 0, it indicates that the service is down. However, I still feel this method might not be very intuitive.

<img width="1907" alt="image" src="https://github.com/megaease/easeprobe/assets/3232275/a75c107a-f787-4653-b707-25a644ca0e49">
<img width="1137" alt="image" src="https://github.com/megaease/easeprobe/assets/3232275/54029418-5fe6-4747-b113-2435a6f4d328">

**Expected behavior**
1.  total{status='down'}  value should increase by 1 each time it's probed
