### ISSUE TITLE
mysql client probe fails to close connections

### ISSUE THREAD

**Issue by proditis** [megaease/easeprobe#56]
**Enviornment:**
 - OS: OpenBSD tester 6.5 GENERIC#13 amd64
 - EaseProbe Version v1.3.0
- MySQL Ver 15.1 Distrib 10.0.38-MariaDB, for OpenBSD (amd64) using readline 4.3

**Describe the bug**
When the mysql client probe is activated the connection stays open which lead to exhaustion of the max connections of the database server.

Based on the config below i get one connection per probe `interval`

**To Reproduce**
Use the mysql client probe on a remote database. I used the following config
```yaml
settings:
  http:
    ip: 127.0.0.1
    port: 8181
    refresh: 5s

  sla:
    schedule : "daily"
    time: "23:59"
    debug: false

  notify:
    dry: true
    retry: # Global settings for retry
      times: 5
      interval: 10s

  probe:
    timeout: 30s
    interval: 1m # probe every minute for all probes
    logfile: "/var/logs/easyprobe.log"

  loglevel: "info"
  timeformat: "2006-01-02 15:04:05 UTC"

client:
  - name: MariaDB Client
    driver: "mysql"
    host: "10.7.0.253:3306"
    username: "user"
    password: "pass"
```
Run easeprobe and observe the connections staying open, one for each minute of uptime.

**Expected behavior**
I expect the connection from each probe to close after its done

**Extra details**
I have looked online for this kind of behavior it it seems the go-mysql driver has seen quite a few of similar reports (of non closing connections). Based on what i found so far, this problem seems to be observed on long running go applications mostly.

My golang knowledge is limited and I could only try a few simple "suggestions" i saw online without success which included:

* Adding these on mysql.go right after `sql.Open()` had: no success
```
        db.SetConnMaxIdleTime(10 * time.Second)
        db.SetConnMaxLifetime(30 * time.Second)
        db.SetMaxOpenConns(1)
        db.SetMaxIdleConns(1)
```
* Removing the `defer` keyword from `db.Close()` and moving it right before the return: no success
* Played with different connection/timeout settings: no success

I will continue to investigate and test just to rule out any configuration issues on the database side and will update here accordingly.
