### ISSUE TITLE
Shell探针中Redis示例有问题

### ISSUE THREAD

**Issue by shengbinxu** [megaease/easeprobe#569]
<img width="779" alt="image" src="https://github.com/user-attachments/assets/a515488f-c93e-4dc5-9de1-9d1ebdca9a6c">
1、REDISCLI_AUTH这个环境变量在redis 3.2版本中无效。
<img width="880" alt="image" src="https://github.com/user-attachments/assets/d1032031-29e4-4012-90d0-cbc474554d58">
建议在示例中做一个说明。
替代方案：在命令中使用-a选项指定密码
<img width="498" alt="image" src="https://github.com/user-attachments/assets/06c0594a-044e-4773-89b4-b4a70d25daaf">

2、当redis server内存不足或者磁盘满了时，使用ping应该是无法检测服务是否异常（没有验证，纯属猜测）。这时候我执行`set key aa` 会执行失败。 此时对应的语法应该是：
```
shell:
  - name: Redis (Local)
    cmd: "redis-cli"
    args:
      - "-h"
      - "xxx.xxx.48.xxx"
      - "-a"
      - "$password"
      - "set"
      - "testtest"
      - "1"
    clean_env: true # Do not pass the OS environment variables to the command
                    # default: false
    env:
      # set the `REDISCLI_AUTH` environment variable for redis password
      - "REDISCLI_AUTH=tidecloudredis"
    # check the command output, if does not contain the PONG, mark the status down
    contain : "OK"
    not_contain: "failure" # response body must NOT contain this string, if it does the probe is considered failed.
    with_output: false # if true, the error message will contain the output, it works for `contain` and `not_contain` field.
    regex: false # if true, the `contain` and `not_contain` will be treated as regular expression. default: false
```

最开始我使用的错误语法是：
```
args:
      - "-h"
      - "10.25.48.xxx"
      - "-a"
      - "$password"
     #  下面的指令应该分三行
      - "set testtest 1"
```

建议在示例中做一个说明
