### ISSUE TITLE
parse_mode broke telegram notification

### ISSUE THREAD

**Issue by envy16** [megaease/easeprobe#628]
**Environment (please complete the following information):**
 - OS: fcos 6.0.18-200.fc36.x86_64
 - EaseProbe Version v2.2.1

**Describe the bug**
I use the following configmap in the k8s cluster:
```yaml
config:
  http:
    - name: OS-01 Dev
      url: https://opensearch-01.example.com:9200/_cluster/health
      method: GET
      content_encoding: text/json
      username: username
      password: password
      insecure: true
      success_code:
        - [200,206]
        - [300,308]
      contain: "green"
      eval:
        doc: JSON
        expression: "x_str('//status')"
      labels:
        env: dev

  settings:
    sla:
      schedule : "daily"
      time: "23:59"

    notify:
      retry:
        times: 5
        interval: 10s

    probe:
      timeout: 10s
      interval: 1m
      failure: 3
      success: 1
      nolinger: true
      alert:
        strategy: "regular"
        factor: 1
        max: 5

  notify:
    telegram:
    - name: "Alerts"
      token: token
      chat_id: "chat_id"
```

When the node is disconnected, an alert is sent, and because of the underscore, part of the alert is highlighted in italics, because this symbol is parsed by markdown.

The reason is in the line "url: https://opensearch-01.example.com:9200/_cluster/health"

![Image](https://github.com/user-attachments/assets/012606d5-de32-4a78-9e81-2247d73df928)

So, in the screenshot you can see that this line appears twice in the notification, because of this, everything between the underscores is highlighted in italics and the underscores are removed.
In fact, the problem does not arise when a notification about unavailability is sent, but when the node is available again, the notification about availability is not sent, and there is an error inside the container:

`time="2025-02-24T10:37:47Z" level=warning msg="[telegram / Alerts / Notification] Retried to send 4/5 - Error response from Telegram - code [400] - msg [{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 73\"}]"`

It looks like the issue is caused by the markdown in this code: https://github.com/megaease/easeprobe/blob/main/notify/telegram/telegram.go#L86C16-L86C24
