### ISSUE TITLE
[feature request]Hot reloading support

### ISSUE THREAD

**Issue by douglarek** [megaease/easeprobe#69]
**Background & X Problem**
Currently (2022-05-05), easeprobe does not support hot reloading, so the problem is that if I just modify the config.yaml file (which can be a frequent action), then I need to restart the application for it to take effect.

**Proposal and Expectation**
We can add a reload option to the configuration file to enable it:

```yaml
reload:
  enabled: true # default is false
  period: 10s # scan interval, default is 10s
```

**Solutions & Y Problems**
We need to not lose the SLA information that the configuration has not changed when the reload is turned on.
