### ISSUE TITLE
Lack of http.refresh and probe.interval settings from config cause panic

### ISSUE THREAD

**Issue by proditis** [megaease/easeprobe#93]
**Enviornment:**
 - OS: [Linux: Linux urandom 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
 - EaseProbe Version [main branch]

**Describe the bug**
I removed some options from the config (expecting easeprobe defaults to kick in) and this caused easeprobe to panic.

![image](https://user-images.githubusercontent.com/4373752/168858551-cd33defb-c23c-465a-b584-4a360031ccb1.png)

I will investigate further to see if i can spot where the bug lies exactly.

**To Reproduce**
1. Use the provided config (see below)
2. start easeprobe `easeprobe -f test.yaml`
3. See error

**Expected behavior**
I would expect easeprobe to fail gracefully. 

* **`test.yaml`**
```yaml
settings:
  sla:
    backups: 3
    debug: false

  notify:
    dry: true
    retry: # Global settings for retry
      times: 5
      interval: 10s

  loglevel: "info"
  timeformat: "2006-01-02 15:04:05 UTC"

http:
 - name: test
   url: http://localhost:8181/

notify:
  discord:
    - name: "Server #Alert"
      webhook: "https://discord.com/api/webhooks//"
      avatar: "https://img.icons8.com/ios/72/appointment-reminders--v1.png"
      thumbnail: "https://freeiconshop.com/wp-content/uploads/edd/notification-flat.png"
      dry: true
      retry:
        times: 3
        interval: 10s
```
